services:
    postgres:
        image: postgres:15-alpine
        container_name: call_panel
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: call_panel
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    springboot:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: call_panel_app
        ports:
            - "8080:8080"
        environment:
            SPRING_PROFILES_ACTIVE: prod
        depends_on:
            - postgres

volumes:
    postgres_data: